### ISSUE TITLE
Hello, I want to ask the file manager component, support upload progress, slice upload, breakpoint recovery? Need to implement it yourself?

### ISSUE THREAD

**Issue by lj2508-com** [webix-hub/webix#334]
Hello, I want to ask the file manager component, support upload progress, slice upload, breakpoint recovery? Need to implement it yourself?

**Comment by lj2508-com** [comment]
When I wrote some java code and found that after constantly creating new folders and returning different values, some of the values ​​I showed were consistent! Can I name this folder when I create a new folder?

**Comment by lj2508-com** [comment]
Sorry, my English is not very good (Google Translate). I checked the documentation and found no related documentation.

**Comment by lVeliarl** [comment]
Hello @lj2508-com,

>I want to ask the file manager component, support upload progress, slice upload, breakpoint recovery? Need to implement it yourself?

By default, the file manager widget doesn't support any of the mentioned features (although I'm not completely sure what you mean by `breakpoint recovery`). Luckily, it is still possible to implement them. 

>slice upload

By ` slice upload` I'm assuming you mean uploading files in chunks? As an option, it is possible to intercept the process of file uploading and use a standalone uploader to send the file in the needed form (chunks in this case). The following example is quite raw and can only demonstrate how the file can be separated and sent to the backend, please take a look: https://snippet.webix.com/33m9oep8. 
Please also note that you will need to handle the separate chunks on the server side in order to receive the original file.

>upload progress

While it is possible to display a [progress bar](https://docs.webix.com/api__link__ui.filemanager_showprogress.html), you will have to either manually set the position of the bar depending on a certain action, or simply make it non-reliant on the actual progress, but make it disappear as soon as it is completed. For instance, the above example (https://snippet.webix.com/33m9oep8) already implements the progress bar in a similar way.

>breakpoint recovery

I'm not quite sure what kind of feature you are looking for here, could you please elaborate on this one?

>Can I name this folder when I create a new folder?

You can intercept the folder creation process with the help of the `onBeforeFolderCreate` event and apply your own custom logic (for instance, show a dialog that would allow you to name the folder before you create it): https://snippet.webix.com/idk0qqj5.
